services:

  api:
    image: doconnor/movies-api:1.0
    container_name: movies-api
    ports:
      - '9000:9000'
    depends_on:
      - mongo
      - redis
    networks:
      - backend
      - front

  mongo:
    image: mongo:8.0-rc
    networks:
      - backend

  mongo-express:
    image: mongo-express:1.0-20-alpine3.19
    depends_on:
      - mongo
    networks:
      - backend
    ports:
      - "8081:8081"